GET http://localhost:3001/characters

###
GET http://localhost:3001/characters?name=Rick

###
GET http://localhost:3001/characters/3

###
GET  http://localhost:3001/episodes

###
GET  http://localhost:3001/episodes/?name=M. Night Shaym-Aliens!

###
GET  http://localhost:3001/locations

###
GET  http://localhost:3001/locations/?type=planet

###
GET https://rickandmortyapi.com/api/character

###
GET https://rickandmortyapi.com/api/episode